---
title: "New York City BCM Analysis"
author: "Caitlin Ward"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 14, fig.height = 6)

library(ggplot2)
library(grid)
library(gridExtra)
library(nimble)
library(plyr)
library(knitr)
library(scales)
library(kableExtra)

# functions to calculate the alarms
source('./scripts/modelCodes.R')

theme_set(theme_bw() + 
    theme(strip.background = element_rect(fill = 'white'),
          strip.text = element_text(size = 16),
          axis.title = element_text(size = 16),
          axis.text = element_text(size = 14)))

```


## Data

```{r}
### read data
nyc <- read.csv('./Data/nycClean.csv')
nyc$date <- as.Date(nyc$date)

ggplot(nyc, aes(x = date, y = smoothedCases, col = factor(peak))) +
    geom_point() + 
    labs(col = "Peak", x = "Date", y = "Incidence")

```


## Gelman Rubin

Number of models remaining with Gelman Rubin > 1.1.

```{r}
grAll <- readRDS('./resultsFinal/grAll.rds')

# which didn't converge
notConverge <- grAll[which(grAll$gr > 1.1),  ]
notConvergeModels <-  notConverge[!duplicated(notConverge[,-which(colnames(notConverge) %in% 
                                                                    c('gr', 'grUpper', 'param'))]),
                                  c('alarmFit', 'infPeriod', 'peak')]
notConvergeModels$noConverge <- 1


table(notConvergeModels$alarmFit,
      notConvergeModels$peak)

```



## Posterior for Alarm Function

```{r}

### load posterior estimates
alarmAll <- readRDS('./resultsFinal/alarmPostAll.rds')


### remove those that did not converge (TEMPORARY)
alarmAll <- merge(alarmAll, notConvergeModels,
                       by = c('alarmFit', 'infPeriod', 'peak'),
                       all.x = T)

alarmAll$noConverge[is.na(alarmAll$noConverge)] <- 0


# format for better plotting
alarmAll$alarmFit <- factor(alarmAll$alarmFit,
                            levels = c('spline', 'gp', 'thresh', 'hill', 'power'),
                            labels = c('Spline', 'Gaussian Process', 
                                       'Threshold', 'Hill', 'Power'))



```

### Peak 1

```{r}
ggplot(subset(nyc, peak== '1'), aes(x = date, y = smoothedCases)) +
    geom_line() + 
    labs(x = "Date", y = "Incidence")

ggplot(subset(alarmAll, peak== '1' & noConverge == 0), aes(x = xAlarm, y = mean)) +  
    geom_line() +
    geom_ribbon(aes(ymin=lower, ymax=upper), alpha=0.3, fill = 'blue') +
    facet_wrap(~alarmFit) +
    labs(x = '30-day incidence', y = 'Alarm')
```


### Peak 2

```{r}
ggplot(subset(nyc, peak== '2'), aes(x = date, y = smoothedCases)) +
    geom_line() + 
    labs(x = "Date", y = "Incidence")

ggplot(subset(alarmAll, peak== '2' & noConverge == 0), aes(x = xAlarm, y = mean)) +  
    geom_line() +
    geom_ribbon(aes(ymin=lower, ymax=upper), alpha=0.3, fill = 'blue') +
    facet_wrap(~alarmFit) +
    labs(x = '30-day incidence', y = 'Alarm')
```


### Peak 3

```{r}
ggplot(subset(nyc, peak== '3'), aes(x = date, y = smoothedCases)) +
    geom_line() + 
    labs(x = "Date", y = "Incidence")

ggplot(subset(alarmAll, peak== '3' & noConverge == 0), aes(x = xAlarm, y = mean)) +  
    geom_line() +
    geom_ribbon(aes(ymin=lower, ymax=upper), alpha=0.3, fill = 'blue') +
    facet_wrap(~alarmFit) +
    labs(x = '30-day incidence', y = 'Alarm')
```



### Peak 4

```{r}
ggplot(subset(nyc, peak== '4'), aes(x = date, y = smoothedCases)) +
    geom_line() + 
    labs(x = "Date", y = "Incidence")

ggplot(subset(alarmAll, peak== '4' & noConverge == 0), aes(x = xAlarm, y = mean)) +  
    geom_line() +
    geom_ribbon(aes(ymin=lower, ymax=upper), alpha=0.3, fill = 'blue') +
    facet_wrap(~alarmFit) +
    labs(x = '30-day incidence', y = 'Alarm')
```

### Full Data

```{r}
ggplot(nyc, aes(x = date, y = smoothedCases)) +
    geom_line() + 
    labs(x = "Date", y = "Incidence")

ggplot(subset(alarmAll, peak== 'full' & noConverge == 0), aes(x = xAlarm, y = mean)) +  
    geom_line() +
    geom_ribbon(aes(ymin=lower, ymax=upper), alpha=0.3, fill = 'blue') +
    facet_wrap(~alarmFit) +
    labs(x = '30-day incidence', y = 'Alarm')
```



## Posterior prediction

Predicted out 100 days after each peak.

```{r}
# merge with posterior predictions
postPredAll <- readRDS('./resultsFinal/postPredAll.rds')

### remove those that did not converge (TEMPORARY)
postPredAll <- merge(postPredAll, notConvergeModels,
                       by = c('alarmFit', 'infPeriod', 'peak'),
                       all.x = T)

postPredAll$noConverge[is.na(postPredAll$noConverge)] <- 0


# format for better plotting
postPredAll$alarmFit <- factor(postPredAll$alarmFit,
                            levels = c('spline', 'gp', 'thresh', 'hill', 
                                       'power', 'basic'),
                            labels = c('Spline', 'Gaussian Process', 
                                       'Threshold', 'Hill', 'Power',
                                       'Basic'))


# add 100 empty
nycNew <- nyc
nycNew[nrow(nycNew)+100,] <- NA

nycNew$timeFull <- 1:nrow(nycNew)


nycNew$timePeak4 <- nycNew$timePeak3 <- nycNew$timePeak2 <- nycNew$timePeak1 <- NA

nycNew$timePeak1[1:(max(which(nycNew$peak == 1)) + 99)] <- 
    as.numeric(rownames(nycNew))[1:(max(which(nycNew$peak == 1)) + 99)]

nycNew$timePeak2[min(which(nycNew$peak == 2)):(max(which(nycNew$peak == 2)) + 99)] <-
    as.numeric(rownames(nycNew))[min(which(nycNew$peak == 2)):(max(which(nycNew$peak == 2)) + 99)] -
    min(which(nycNew$peak == 2)) + 1

nycNew$timePeak3[min(which(nycNew$peak == 3)):(max(which(nycNew$peak == 3)) + 99)] <-
    as.numeric(rownames(nycNew))[min(which(nycNew$peak == 3)):(max(which(nycNew$peak == 3)) + 99)] -
    min(which(nycNew$peak == 3)) + 1

nycNew$timePeak4[min(which(nycNew$peak == 4)):(max(which(nycNew$peak == 4)) + 99)] <-
    as.numeric(rownames(nycNew))[min(which(nycNew$peak == 4)):(max(which(nycNew$peak == 4)) + 99)] -
    min(which(nycNew$peak == 4)) + 1

```

### Peak 1

```{r}
ggplot() +
  geom_line(data = nycNew, aes(x = timePeak1, y = smoothedCases)) + 
   geom_line(data = subset(postPredAll, peak == '1' & noConverge == 0),
            aes(x = time, y = mean), col = 'red', size = 1) + 
   geom_ribbon(data= subset(postPredAll, peak == '1' & noConverge == 0),
               aes(x = time, ymin=lower, ymax=upper), alpha=0.3, fill = 'red') +
  facet_wrap(~alarmFit, nrow = 1)+
    ylim(0, 6000)
```


### Peak 2

```{r}
ggplot() +
  geom_line(data = nycNew, aes(x = timePeak2, y = smoothedCases)) + 
   geom_line(data = subset(postPredAll, peak == '2' & noConverge == 0),
            aes(x = time, y = mean), col = 'red', size = 1) + 
   geom_ribbon(data= subset(postPredAll, peak == '2' & noConverge == 0),
               aes(x = time, ymin=lower, ymax=upper), alpha=0.3, fill = 'red') +
  facet_wrap(~alarmFit, nrow = 1)+
    ylim(0, 6000)
```

### Peak 3

```{r}
ggplot() +
  geom_line(data = nycNew, aes(x = timePeak3, y = smoothedCases)) + 
   geom_line(data = subset(postPredAll, peak == '3' & noConverge == 0),
            aes(x = time, y = mean), col = 'red', size = 1) + 
   geom_ribbon(data= subset(postPredAll, peak == '3' & noConverge == 0),
               aes(x = time, ymin=lower, ymax=upper), alpha=0.3, fill = 'red') +
  facet_wrap(~alarmFit, nrow = 1)
```

### Peak 4

```{r}
ggplot() +
  geom_line(data = nycNew, aes(x = timePeak4, y = smoothedCases)) + 
   geom_line(data = subset(postPredAll, peak == '4' & noConverge == 0),
            aes(x = time, y = mean), col = 'red', size = 1) + 
   geom_ribbon(data= subset(postPredAll, peak == '4' & noConverge == 0),
               aes(x = time, ymin=lower, ymax=upper), alpha=0.3, fill = 'red') +
  facet_wrap(~alarmFit, nrow = 1)
    # ylim(0, 8000)
```



### Full

```{r}
ggplot() +
  geom_line(data = nycNew, aes(x = timeFull, y = smoothedCases)) + 
   geom_line(data = subset(postPredAll, peak == 'full' & noConverge == 0),
            aes(x = time, y = mean), col = 'red', size = 1) + 
   geom_ribbon(data= subset(postPredAll, peak == 'full' & noConverge == 0),
               aes(x = time, ymin=lower, ymax=upper), alpha=0.3, fill = 'red') +
  facet_wrap(~alarmFit, nrow = 1)
    # ylim(0, 8000)
```



## WAIC

```{r}
options(scipen=20)
waicAll <- readRDS('./resultsFinal/waicAll.rds')



### remove those that did not converge (TEMPORARY)
waicAll <- merge(waicAll, notConvergeModels,
                       by = c('alarmFit', 'infPeriod', 'peak'),
                       all.x = T)

waicAll$noConverge[is.na(waicAll$noConverge)] <- 0

waicAll <- waicAll[order(waicAll$peak, waicAll$waic),]
# summaries of WAIC values by model
waicAll$waic <- round(waicAll$waic, 2)
waicAll$lppd <- round(waicAll$lppd, 2)
waicAll$pWAIC <- round(waicAll$pWAIC, 2)

kable(waicAll[,-which(colnames(waicAll) %in% c('peak', 'infPeriod'))], 
      row.names = F) %>% 
  pack_rows(index = table(waicAll$peak))
```




