---
title: "Untitled"
author: "Caitlin Ward"
date: "2022-08-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Posterior for beta\[t\] when modeled explicitly

For one simulation.

```{r}
# beta[t] depends on epidemic trajectory
simNumber <- 1
times <- 1:50

# get true epidemic curves for each scenario
trueCurveThresh14 <- readRDS(paste0('./Data/thresh_exp_14.rds'))[simNumber,times]
trueCurveThresh30 <- readRDS(paste0('./Data/thresh_exp_30.rds'))[simNumber,times]
trueCurveHill14 <- readRDS(paste0('./Data/hill_exp_14.rds'))[simNumber,times]
trueCurveHill30 <- readRDS(paste0('./Data/hill_exp_30.rds'))[simNumber,times]
trueCurvePower14 <- readRDS(paste0('./Data/power_exp_14.rds'))[simNumber,times]
trueCurvePower30 <- readRDS(paste0('./Data/power_exp_30.rds'))[simNumber,times]


# using epidemic trajectory and true parameters, find value of alarm[t]/beta[t]
paramsTruth <- read.xlsx('simParamsSummary.xlsx')
paramsTruth <- paramsTruth[paramsTruth$infPeriod == 'exp',]

N <- 1e6
trueAlarmThresh14 <- thresholdAlarm(movingAverage(trueCurveThresh14, 14),
                                    N = N, 
                                    delta = paramsTruth$delta[
                                        (paramsTruth$alarmGen == 'thresh' & 
                                             paramsTruth$smoothWindow == 14)],
                                    H = paramsTruth$H[
                                        (paramsTruth$alarmGen == 'thresh' & 
                                             paramsTruth$smoothWindow == 14)])
trueAlarmThresh30 <- thresholdAlarm(movingAverage(trueCurveThresh30, 30), 
                                    N = N, 
                                    delta = paramsTruth$delta[
                                        (paramsTruth$alarmGen == 'thresh' & 
                                             paramsTruth$smoothWindow == 30)],
                                    H = paramsTruth$H[
                                        (paramsTruth$alarmGen == 'thresh' & 
                                             paramsTruth$smoothWindow == 30)])
trueAlarmHill14 <- hillAlarm(movingAverage(trueCurveHill14, 14), 
                             nu = paramsTruth$nu[
                                 (paramsTruth$alarmGen == 'hill' & 
                                      paramsTruth$smoothWindow == 14)],
                             x0 = paramsTruth$x0[
                                 (paramsTruth$alarmGen == 'hill' & 
                                      paramsTruth$smoothWindow == 14)],
                             delta = paramsTruth$delta[
                                 (paramsTruth$alarmGen == 'hill' & 
                                      paramsTruth$smoothWindow == 14)])
trueAlarmHill30 <- hillAlarm(movingAverage(trueCurveHill30, 30), 
                             nu = paramsTruth$nu[
                                 (paramsTruth$alarmGen == 'hill' & 
                                      paramsTruth$smoothWindow == 30)],
                             x0 = paramsTruth$x0[
                                 (paramsTruth$alarmGen == 'hill' & 
                                      paramsTruth$smoothWindow == 30)],
                             delta = paramsTruth$delta[
                                 (paramsTruth$alarmGen == 'hill' & 
                                      paramsTruth$smoothWindow == 30)])
trueAlarmPower14 <- powerAlarm(movingAverage(trueCurvePower14, 14), 
                               N = N, 
                               k = paramsTruth$k[
                                   (paramsTruth$alarmGen == 'power' & 
                                        paramsTruth$smoothWindow == 14)])
trueAlarmPower30 <- powerAlarm(movingAverage(trueCurvePower30, 30),
                               N = N, 
                               k = paramsTruth$k[
                                   (paramsTruth$alarmGen == 'power' & 
                                        paramsTruth$smoothWindow == 30)])

trueAlarmsSim <- data.frame(time = rep(times, 6),
                            trueAlarm = c(trueAlarmThresh14,
                                          trueAlarmThresh30,
                                          trueAlarmHill14,
                                          trueAlarmHill30,
                                          trueAlarmPower14,
                                          trueAlarmPower30),
                            alarmGen = c(rep('thresh', length(times)*2),
                                         rep('hill', length(times)*2),
                                         rep('power', length(times)*2)),
                            smoothWindow = rep(rep(c(14, 30), each = length(times)), 3),
                            epiSize = 'small')

# from true alarms, get true beta[t]
trueBeta <- trueAlarmsSim
trueBeta$trueBeta <- paramsTruth$beta[1] * (1 - trueBeta$trueAlarm)

### load posterior estimates
betaPostAll <- readRDS('./resultsFinal/betaPostAll.rds')
betaPostAll <- betaPostAll[betaPostAll$simNumber == simNumber,]


### remove those that did not converge (TEMPORARY)
betaPostAll <- merge(betaPostAll, notConvergeModels,
                     by = c('alarmGen', 'alarmFit',  'prior',
                            'smoothWindow', 'epiSize', 'simNumber'),
                     all.x = T)

betaPostAll$noConverge[is.na(betaPostAll$noConverge)] <- 0

notConvergeBeta <-  betaPostAll[!duplicated(betaPostAll[,
                                                        c('alarmGen', 'alarmFit',
                                                          'prior', 'smoothWindow', 'epiSize', 'simNumber')]),]


betaPostAll$prior <- factor(betaPostAll$prior, 
                            labels=c('True/strong', 'Wrong/strong',
                                     'True/vague', 'Wrong/vague'))
```

### 14-day Smoothing

```{r}
ggplot() +  
    geom_line(data = subset(betaPostAll, smoothWindow == 14 & noConverge == 0), 
              aes(x = time, y = mean, group = simNumber), 
              col = 'red') +
    geom_ribbon(data=subset(betaPostAll, smoothWindow == 14 & noConverge == 0),
                aes(x = time, ymin = lower, ymax = upper), 
                alpha = 0.3, fill = 'red') +
    geom_line(data = subset(trueBeta, smoothWindow == 14), 
              aes(x = time, y = trueBeta), col = 'black') +
    facet_grid(prior +~smoothWindow + alarmGen, labeller = "label_both", scales = 'free')
```

### 30-day Smoothing

```{r}
ggplot() +  
    geom_line(data = subset(betaPostAll, smoothWindow == 30 & noConverge == 0), 
              aes(x = time, y = mean, group = simNumber), 
              col = 'red') +
    geom_ribbon(data=subset(betaPostAll, smoothWindow == 30 & noConverge == 0),
                aes(x = time, ymin = lower, ymax = upper), 
                alpha = 0.3, fill = 'red') +
    geom_line(data = subset(trueBeta, smoothWindow == 30), 
              aes(x = time, y = trueBeta), col = 'black') +
    facet_grid(prior~smoothWindow + alarmGen, labeller = "label_both", scales = 'free')
```

## WAIC Comparison

```{r}
waicAll <- readRDS('./resultsFinal/waicAll.rds')

### remove those that did not converge (TEMPORARY)
waicAll <- merge(waicAll, notConvergeModels,
                 by = c('alarmGen', 'alarmFit', 
                        'prior', 'smoothWindow', 'simNumber'),
                 all.x = T)

waicAll$noConverge[is.na(waicAll$noConverge)] <- 0


# summaries of WAIC values by model
waicSummaries <- ddply(waicAll, .(alarmGen, alarmFit, smoothWindow, prior),
                       summarize,
                       nConverge = length(waic[noConverge == 0]),
                       mean_WAIC = mean(waic[noConverge == 0]),
                       mean_lppd = mean(lppd[noConverge == 0]),
                       mean_pWAIC = mean(pWAIC[noConverge == 0]))
waicSummaries <- waicSummaries[order(waicSummaries$mean_WAIC),]
```

### Threshold alarm with 14-day smoothing window

```{r}
tmp <- subset(waicSummaries, alarmGen == 'thresh' & smoothWindow == 14)
tmp <- tmp[-which(colnames(tmp) %in% c('alarmGen', 'smoothWindow'))]
kable(tmp, row.names = F)
```

### Threshold alarm with 30-day smoothing window

```{r}
tmp <- subset(waicSummaries, alarmGen == 'thresh' & smoothWindow == 30)
tmp <- tmp[-which(colnames(tmp) %in% c('alarmGen', 'smoothWindow'))]
kable(tmp, row.names = F)
```

### Hill alarm with 14-day smoothing window

```{r}
tmp <- subset(waicSummaries, alarmGen == 'hill' & smoothWindow == 14)
tmp <- tmp[-which(colnames(tmp) %in% c('alarmGen', 'smoothWindow'))]
kable(tmp, row.names = F)
```

### Hill alarm with 30-day smoothing window

```{r}
tmp <- subset(waicSummaries, alarmGen == 'hill' & smoothWindow == 30)
tmp <- tmp[-which(colnames(tmp) %in% c('alarmGen', 'smoothWindow'))]
kable(tmp, row.names = F)
```

### Power alarm with 14-day smoothing window

```{r}
tmp <- subset(waicSummaries, alarmGen == 'power' & smoothWindow == 14)
tmp <- tmp[-which(colnames(tmp) %in% c('alarmGen', 'smoothWindow'))]
kable(tmp, row.names = F)
```

### Power alarm with 30-day smoothing window

```{r}
tmp <- subset(waicSummaries, alarmGen == 'power' & smoothWindow == 30)
tmp <- tmp[-which(colnames(tmp) %in% c('alarmGen', 'smoothWindow'))]
kable(tmp, row.names = F)
```
